-- =============================================================================
--  MoaMat — Schéma de la base « Gestion du matériel » — Royal Moana
--  Cible : Supabase / PostgreSQL 15+
-- =============================================================================
--
--  Nommage des tables et des colonnes : conforme à
--  Access_Data/Nommage_tables_MOANA.md (colonne « Nom proposé ») et à
--  Access_Data/_dictionnaire_tables.csv.
--
--  Ce schéma reproduit FIDÈLEMENT la structure de l'export Access. La
--  normalisation métier (fusion des tables *_sortie_inventaire, suppression des
--  colonnes calculées comme age_calcule / sortie_autorisee, typage fin des
--  mesures « 12 Li » / « 14,3 ») est un chantier distinct — cf. Nommage §4.
--
--  Les 8 tables préfixées zz_ de l'export ne sont volontairement PAS créées :
--  ce sont des tables de travail Access, sans vocation à exister dans la cible.
--
--  Typage retenu :
--    * identifiants           -> bigint GENERATED BY DEFAULT AS IDENTITY
--                               (les id Access d'origine sont réinjectés par
--                                initial_load.sql, puis les séquences recalées)
--    * drapeaux 0/1           -> boolean
--    * montants « propres »   -> numeric(12,2)
--    * dates                  -> date (sentinelles Access nettoyées au chargement)
--    * mesures « sales »      -> text (verbatim)
--    * tout le reste          -> text
--
--  RLS : activé sur toutes les tables avec une policy PERMISSIVE de démarrage
--  (anon + authenticated, lecture/écriture). À remplacer par le modèle à 4 rôles
--  de l'analyse fonctionnelle avant mise en production.
--
--  DESTRUCTIF : chaque table est supprimée (drop ... cascade) puis recréée.
--  À exécuter avant db/initial_load.sql. Ré-exécutable sans erreur.
-- =============================================================================

begin;

-- =============================================================================
--  1. Référentiels
-- =============================================================================

drop table if exists ref_action_compresseur cascade;
create table ref_action_compresseur (
    id      bigint generated by default as identity primary key,
    libelle text
);

drop table if exists ref_gaz cascade;
create table ref_gaz (
    id      bigint generated by default as identity primary key,
    libelle text
);

drop table if exists ref_local_didactique cascade;
create table ref_local_didactique (
    id      bigint generated by default as identity primary key,
    libelle text
);

drop table if exists ref_regle_requalification cascade;
create table ref_regle_requalification (
    id                       bigint generated by default as identity primary key,
    famille_bouteille        text,
    periodicite_optique      text,
    periodicite_hydraulique  text,
    reglementation           text,
    remarque                 text
);

drop table if exists ref_site cascade;
create table ref_site (
    id      bigint generated by default as identity primary key,
    libelle text
);

drop table if exists ref_site_web cascade;
create table ref_site_web (
    num             bigint generated by default as identity primary key,
    websites_visited text
);

drop table if exists ref_tarif_requalification cascade;
create table ref_tarif_requalification (
    id                 bigint generated by default as identity primary key,
    libelle_prestation text,
    sigle              text,
    tarif_eur          numeric(12,2),
    annee              integer,
    indexation_pct     numeric(12,2)
);

-- =============================================================================
--  2. Bouteilles
-- =============================================================================

drop table if exists bouteille cascade;
create table bouteille (
    id                     bigint generated by default as identity primary key,
    controle_effectue      boolean,
    site                   text,
    code_club              text,
    num_peint              text,
    num_serie_fabricant    text,
    num_robinet            text,
    famille                text,
    local                  text,
    filetage               text,
    double_sortie          boolean,
    modele                 text,
    sangles                text,
    marque                 text,
    destination            text,
    volume_nominal_l       text,
    pression_service_bar   text,
    tare_kg                text,
    capacite_reelle_l      text,
    sortie_autorisee       boolean,
    a_controler            boolean,
    remarque               text,
    date_mise_en_service   date,
    date_echeance          date,
    age_calcule            text,
    est_declassee          boolean,
    date_declassement      date,
    autorite_declassement  text,
    a_requalifier          boolean
);

drop table if exists bouteille_sortie_inventaire cascade;
create table bouteille_sortie_inventaire (
    id                     bigint generated by default as identity primary key,
    controle_effectue      boolean,
    site                   text,
    code_club              text,
    num_peint              text,
    num_serie_fabricant    text,
    num_robinet            text,
    famille                text,
    local                  text,
    filetage               text,
    double_sortie          boolean,
    modele                 text,
    sangles                text,
    marque                 text,
    volume_nominal_l       text,
    pression_service_bar   text,
    tare_kg                text,
    capacite_reelle_l      text,
    sortie_autorisee       boolean,
    a_controler            boolean,
    remarque               text,
    date_mise_en_service   date,
    date_echeance          date,
    age_calcule            text,
    est_declassee          boolean,
    date_declassement      date,
    autorite_declassement  text,
    a_requalifier          boolean
);

drop table if exists bouteille_requalification cascade;
create table bouteille_requalification (
    id                        bigint generated by default as identity primary key,
    bouteille_id              bigint,
    date_operation            date,
    type_operation            text,
    cout_eur                  numeric(12,2),
    date_echeance_suivante    date,
    type_echeance_suivante_id bigint,
    remarque                  text,
    num_certificat            text
);

drop table if exists bouteille_membre cascade;
create table bouteille_membre (
    id                        bigint generated by default as identity primary key,
    date_rendez_vous          date,
    nom                       text,
    prenom                    text,
    gsm                       text,
    num_bouteille             text,
    gaz_id                    bigint,
    date_derniere_epreuve     date,
    type_derniere_epreuve_id  bigint,
    remarque_id               text,
    date_echeance             date,
    type_echeance_suivante_id bigint,
    flag_aujourdhui           boolean,
    tarif_id                  bigint,
    remarque2_id              text,
    num_officiel              text,
    num_ordre_travail         text
);

-- =============================================================================
--  3. Détendeurs
-- =============================================================================

drop table if exists detendeur cascade;
create table detendeur (
    id                      bigint generated by default as identity primary key,
    controle_effectue       boolean,
    date_dernier_controle   date,
    num_ordre               text,
    section                 text,
    date_achat              date,
    code_club               text,
    marque                  text,
    type_connexion          text,
    modele_premier_etage    text,
    a_premier_etage         boolean,
    num_serie_premier_etage text,
    a_second_etage          boolean,
    modele_second_etage     text,
    num_serie_second_etage  text,
    a_octopus               boolean,
    modele_octopus          text,
    num_serie_octopus       text,
    a_inflateur             boolean,
    a_manometre             boolean,
    sortie_autorisee        boolean,
    reserve_enfants         boolean,
    remarque                text,
    est_declasse            boolean
);

drop table if exists detendeur_sortie_inventaire cascade;
create table detendeur_sortie_inventaire (
    id                      bigint generated by default as identity primary key,
    controle_effectue       boolean,
    date_dernier_controle   date,
    num_ordre               text,
    section                 text,
    date_achat              date,
    code_club               text,
    marque                  text,
    type_connexion          text,
    modele_premier_etage    text,
    a_premier_etage         boolean,
    num_serie_premier_etage text,
    a_second_etage          boolean,
    modele_second_etage     text,
    num_serie_second_etage  text,
    a_octopus               boolean,
    modele_octopus          text,
    num_serie_octopus       text,
    a_inflateur             boolean,
    a_manometre             boolean,
    sortie_autorisee        boolean,
    reserve_enfants         boolean,
    remarque                text,
    est_declasse            boolean
);

drop table if exists detendeur_intervention cascade;
create table detendeur_intervention (
    id                     bigint generated by default as identity primary key,
    detendeur_id           bigint,
    date_intervention      date,
    piece_jointe_id        bigint,
    ctrl_manometre         text,
    ctrl_detendeur         text,
    ctrl_octopus           text,
    ctrl_inflateur         text,
    ctrl_visuel_flexibles  text,
    remarque               text,
    cout_eur               numeric(12,2)
);

-- =============================================================================
--  4. Autres familles de matériel
-- =============================================================================

drop table if exists gilet cascade;
create table gilet (
    id                   bigint generated by default as identity primary key,
    est_manquant         boolean,
    section              text,
    code_club            text,
    marque               text,
    couleur              text,
    date_achat           date,
    sortie_autorisee     boolean,
    taille               text,
    emplacement_remarque text,
    num_serie_fabricant  text,
    est_declasse         boolean,
    marquage             text
);

drop table if exists gilet_sortie_inventaire cascade;
create table gilet_sortie_inventaire (
    id                   bigint generated by default as identity primary key,
    est_manquant         boolean,
    section              text,
    code_club            text,
    marque               text,
    couleur              text,
    date_achat           date,
    sortie_autorisee     boolean,
    taille               text,
    emplacement_remarque text,
    num_serie_fabricant  text,
    est_declasse         boolean
);

drop table if exists petit_materiel cascade;
create table petit_materiel (
    id             bigint generated by default as identity primary key,
    section        text,
    local          text,
    marque         text,
    modele         text,
    couleur        text,
    famille        text,
    taille         text,
    quantite       numeric(12,2),
    pointure       text,
    prix_tvac_eur  numeric(12,2),
    date_achat     date,
    code_club      text,
    est_declasse   boolean,
    declasse_par   text
);

drop table if exists materiel_didactique cascade;
create table materiel_didactique (
    id                  bigint generated by default as identity primary key,
    date_achat          date,
    code_club           text,
    quantite            numeric(12,2),
    designation         text,
    num_serie_fabricant text,
    modele              text,
    local_id            bigint,
    site_id             bigint,
    est_declasse        boolean,
    date_declassement   date,
    declasse_par        text
);

drop table if exists piece_detachee cascade;
create table piece_detachee (
    id                   bigint generated by default as identity primary key,
    reference_fournisseur text,
    dimension            text,
    destination          text,
    colisage             text,
    prix_unitaire_eur    numeric(12,2),
    fournisseur          text,
    stock                numeric(12,2),
    emplacement          text,
    utilisation          text,
    url_commande         text,
    piece_jointe_id      bigint
);

-- =============================================================================
--  5. Compresseurs
-- =============================================================================

drop table if exists compresseur_releve cascade;
create table compresseur_releve (
    id                 bigint generated by default as identity,
    site               text not null,
    date_releve        date,
    index_heures_avant text,
    action_id          bigint,
    index_heures_apres text,
    delta_heures       text,
    remarque           text,
    piece_jointe_id    bigint,
    montant_eur        numeric(12,2),
    reference_facture  text,
    fournisseur        text,
    primary key (id, site)   -- clé composite : l'id d'origine n'est unique que par site (fusion Sg + Fl)
);

-- =============================================================================
--  6. Achats
-- =============================================================================

drop table if exists achat_facture cascade;
create table achat_facture (
    id                  bigint generated by default as identity primary key,
    designation         text,
    categorie_analytique text,
    montant_eur         numeric(12,2),
    num_facture         text,
    fournisseur         text,
    date_facture        date,
    piece_jointe_id     bigint
);

drop table if exists achat_reception cascade;
create table achat_reception (
    id_achats         bigint generated by default as identity primary key,
    qu_achetee        integer,
    qu_recue          integer,
    qu_a_recevoir     integer,
    definition_materiel text,
    prix_individuel   numeric(12,2)
);

drop table if exists achat_2022_non_integre cascade;
create table achat_2022_non_integre (
    id                    bigint generated by default as identity primary key,
    type_de_materiel      text,
    description           text,
    destination           text,
    capacite              text,
    type_de_btl           text,
    type_de_connexion     text,
    materiel_associe_0    text,
    materiel_associe_1    text,
    materiel_associe_2    text,
    materiel_associe_3    text,
    quantite              numeric(12,2),
    marque                text,
    type                  text,
    prix_unitaire         numeric(12,2),
    lieu                  text,
    local                 text,
    conditionnement       text,
    annee_achat           text,
    remarque              text,
    num_de_serie          text,
    poids                 text,
    pression_service      text,
    pression_de_reepreuve text,
    date_reepreuve_initiale date
);

drop table if exists devis_ligne cascade;
create table devis_ligne (
    id                        bigint generated by default as identity primary key,
    date_creation             date,
    fournisseur               text,
    reference_besoin          text,
    materiel_demande          text,
    quantite                  numeric(12,2),
    marque                    text,
    montant_tvac_eur          numeric(12,2),
    montant_htva_eur_corrompu bigint,   -- valeur corrompue (134217728) conservée pour mémoire
    date_reponse              text,     -- format dd/MM/yyyy hétérogène : gardé en texte
    num_devis                 text
);

drop table if exists fournisseur cascade;
create table fournisseur (
    id         bigint generated by default as identity primary key,
    nom        text,
    specialite text
);

-- =============================================================================
--  7. Personnes
-- =============================================================================

drop table if exists personne cascade;
create table personne (
    id     bigint generated by default as identity primary key,
    nom    text,
    prenom text,
    email  text
);

drop table if exists utilisateur cascade;
create table utilisateur (
    id                          bigint generated by default as identity primary key,
    nom_complet                 text,
    email                       text,
    gsm                         text,
    mot_de_passe_a_ne_pas_migrer text,  -- mot de passe en clair : jamais alimenté (à détruire)
    role                        text
);

drop table if exists pret cascade;
create table pret (
    id                 bigint generated by default as identity primary key,
    nom_complet        text,
    brevet             text,
    gsm                text,
    email              text,
    date_pret          date,
    date_retour_prevue date,
    gilet_code         text,
    detendeur_code     text,
    bouteille_code     text,
    date_retour_reelle date,
    responsable        text,
    est_cloture        boolean
);

-- =============================================================================
--  8. Index sur les colonnes de type clé étrangère
-- =============================================================================

create index if not exists ix_bouteille_requalification_bouteille_id      on bouteille_requalification (bouteille_id);
create index if not exists ix_bouteille_membre_gaz_id                     on bouteille_membre (gaz_id);
create index if not exists ix_detendeur_intervention_detendeur_id         on detendeur_intervention (detendeur_id);
create index if not exists ix_materiel_didactique_local_id                on materiel_didactique (local_id);
create index if not exists ix_materiel_didactique_site_id                 on materiel_didactique (site_id);
create index if not exists ix_compresseur_releve_action_id                on compresseur_releve (action_id);

-- =============================================================================
--  9. Row Level Security — policies PERMISSIVES de démarrage
--  ⚠ À remplacer par le modèle à 4 rôles (Super-admin / Admin / Gestion /
--    Lecture) de l'analyse fonctionnelle avant toute ouverture réelle.
-- =============================================================================

do $$
declare
    t text;
    tables text[] := array[
        'ref_action_compresseur','ref_gaz','ref_local_didactique','ref_regle_requalification',
        'ref_site','ref_site_web','ref_tarif_requalification',
        'bouteille','bouteille_sortie_inventaire','bouteille_requalification','bouteille_membre',
        'detendeur','detendeur_sortie_inventaire','detendeur_intervention',
        'gilet','gilet_sortie_inventaire','petit_materiel','materiel_didactique','piece_detachee',
        'compresseur_releve',
        'achat_facture','achat_reception','achat_2022_non_integre','devis_ligne','fournisseur',
        'personne','utilisateur','pret'
    ];
begin
    foreach t in array tables loop
        execute format('alter table %I enable row level security;', t);
        execute format('drop policy if exists moamat_dev_all on %I;', t);
        execute format(
            'create policy moamat_dev_all on %I for all to anon, authenticated using (true) with check (true);',
            t);
    end loop;
end $$;

commit;

-- =============================================================================
--  10. Clés étrangères — À ACTIVER APRÈS la reprise et le nettoyage des
--      orphelins. L'export Access contient des références incohérentes
--      (bouteille_id pointant vers des bouteilles sorties d'inventaire,
--      *_id de référentiels hors liste, etc.). Décommenter bloc par bloc
--      une fois les données arbitrées.
-- =============================================================================

-- alter table bouteille_requalification
--     add constraint fk_bouteille_requalification_bouteille
--     foreign key (bouteille_id) references bouteille (id);

-- alter table bouteille_requalification
--     add constraint fk_bouteille_requalification_type_echeance
--     foreign key (type_echeance_suivante_id) references ref_tarif_requalification (id);

-- alter table bouteille_membre
--     add constraint fk_bouteille_membre_gaz
--     foreign key (gaz_id) references ref_gaz (id);

-- alter table detendeur_intervention
--     add constraint fk_detendeur_intervention_detendeur
--     foreign key (detendeur_id) references detendeur (id);

-- alter table materiel_didactique
--     add constraint fk_materiel_didactique_local
--     foreign key (local_id) references ref_local_didactique (id);

-- alter table materiel_didactique
--     add constraint fk_materiel_didactique_site
--     foreign key (site_id) references ref_site (id);

-- alter table compresseur_releve
--     add constraint fk_compresseur_releve_action
--     foreign key (action_id) references ref_action_compresseur (id);
